import type { NextPage } from "next";
import Head from "next/head";
import Catalog from "../components/Catalog";
import CatalogItem from "../components/Catalog/Item";
import fetcher from "../utils/fetcher";

const Home: NextPage<{ items: Catalog.ProductName[] }> = ({ items }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Catalog>
          {items.map((item) => (
            <CatalogItem key={item} name={item} />
          ))}
        </Catalog>
      </main>
    </>
  );
};

export const getServerSideProps = async () => {
  const catalog: Catalog = await fetcher(
    "https://s3.us-west-2.amazonaws.com/secure.notion-static.com/be5dc0c9-4f60-4303-a89e-3ffec4969245/data.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220328%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220328T104908Z&X-Amz-Expires=86400&X-Amz-Signature=e3d8745d92bd8c1fa090674ec9c8c43d7d7b73731fcdbabda3abb0c7ebf206d9&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22data.json%22&x-id=GetObject"
  );

  const items = catalog.data.allProductReference.map((i) => i.display_name);

  return {
    props: {
      items,
    },
  };
};

export default Home;
